# Data Generation and Initial Dataset Creation

In this section, we create a synthetic dataset using `pandas` and `numpy`. This dataset simulates employee records with various attributes such as age, salary, department, joining date, and performance score.

---

### Steps:

- **Set a random seed** for reproducibility.
- Create **500 datapoints** with the following fields:
  - `id`: Unique identifier from 1 to 500.
  - `age`: Random integers between 18 and 70.
  - `salary`: Normally distributed values with mean 50,000 and std deviation 15,000.
  - `department`: Randomly assigned from 4 departments.
  - `join_date`: Random dates within 3 years starting from January 1, 2020.
  - `performance_score`: Randomly chosen from 1 to 5, with some missing values (`NaN`).

- Add a few **duplicate rows** intentionally to simulate real-world data cleaning challenges.

---

_**Step 1: Generate the sample data**_

In [1]:
import pandas as pd
import numpy as np

np.random.seed(42)

# Create 500 datapoints
n = 500
df = pd.DataFrame({
    'id': range(1, n+1),
    'age': np.random.randint(18, 70, size=n),
    'salary': np.random.normal(50000, 15000, size=n).round(2),
    'department': np.random.choice(['HR', 'Engineering', 'Sales', 'Marketing'], size=n),
    'join_date': pd.to_datetime('2020-01-01') + pd.to_timedelta(np.random.randint(0, 365*3, size=n), unit='D'),
    'performance_score': np.random.choice([np.nan, 1, 2, 3, 4, 5], size=n, p=[0.1, 0.15, 0.2, 0.3, 0.15, 0.1])
})

# Add some duplicates for cleaning demo
df = pd.concat([df, df.iloc[:5]], ignore_index=True)

df.head()

   id  age    salary department  join_date  performance_score
0   1   56  81832.34         HR 2022-08-31                3.0
1   2   69  65486.98      Sales 2022-11-11                1.0
2   3   46  27209.45      Sales 2022-04-28                3.0
3   4   32  42736.49  Marketing 2022-01-17                3.0
4   5   60  69003.67      Sales 2022-09-15                1.0

_**Step 2: Code examples grouped by function categories**_

# 🔍 2. Exploring Data

_Before diving into analysis or cleaning, it's important to understand the structure and contents of your dataset. Below are some common commands to get an overview:_

- `df.head()`: Display the first 5 rows to get a quick look at the data.
- `df.tail()`: Display the last 5 rows to check data consistency.
- `df.info()`: Summary of the dataframe including data types and non-null counts.
- `df.describe()`: Statistical summary (mean, std, min, max, quartiles) for numeric columns.
- `df.shape`: Returns the number of rows and columns in the dataframe.
- `df.columns`: Lists all column names.
- `df.dtypes`: Shows the data type of each column.
- `df.nunique()`: Number of unique values in each column, useful for understanding categorical variables.
- `df.memory_usage()`: Shows how much memory each column uses.

---

In [2]:
df.head()

   id  age    salary department  join_date  performance_score
0   1   56  81832.34         HR 2022-08-31                3.0
1   2   69  65486.98      Sales 2022-11-11                1.0
2   3   46  27209.45      Sales 2022-04-28                3.0
3   4   32  42736.49  Marketing 2022-01-17                3.0
4   5   60  69003.67      Sales 2022-09-15                1.0

In [3]:
df.tail()

     id  age    salary department  join_date  performance_score
500   1   56  81832.34         HR 2022-08-31                3.0
501   2   69  65486.98      Sales 2022-11-11                1.0
502   3   46  27209.45      Sales 2022-04-28                3.0
503   4   32  42736.49  Marketing 2022-01-17                3.0
504   5   60  69003.67      Sales 2022-09-15                1.0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 505 entries, 0 to 504
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 505 non-null    int64
 1   age                505 non-null    int32
 2   salary             505 non-null    float64
 3   department         505 non-null    object
 4   join_date          505 non-null    datetime64[ns]
 5   performance_score  452 non-null    float64
dtypes: datetime64[ns](1), float64(2), int32(1), int64(1), object(1)
memory usage: 21.8+ KB

In [5]:
df.describe()

,id,age,salary,join_date,performance_score
count,505.000000,505.00000,505.000000,505,452.000000
mean,248.049505,44.30297,49633.953703,2021-07-22 14:32:33.267326720,2.765487
min,1.000000,18.00000,1380.990000,2020-01-02 00:00:00,1.000000
25%,122.000000,32.00000,39307.310000,2020-11-03 00:00:00,2.000000
50%,248.000000,45.00000,49686.480000,2021-08-06 00:00:00,3.000000
75%,374.000000,57.00000,59491.730000,2022-05-08 00:00:00,4.000000
max,500.000000,69.00000,96183.210000,2022-12-29 00:00:00,5.000000
std,145.841046,15.03743,14979.868131,NaN,1.225326

In [6]:
df.shape

(505, 6)

In [7]:
df.columns

Index(['id', 'age', 'salary', 'department', 'join_date', 'performance_score'], dtype='object')

In [8]:
df.dtypes

id                            int64
age                           int32
salary                      float64
department                   object
join_date            datetime64[ns]
performance_score           float64
dtype: object

In [9]:
df.nunique()

id                   500
age                   52
salary               500
department             4
join_date            381
performance_score      5
dtype: int64

In [10]:
df.memory_usage()

Index                 132
id                   4040
age                  2020
salary               4040
department           4040
join_date            4040
performance_score    4040
dtype: int64

# 🧹 3. Cleaning Data

_Cleaning data is crucial for accurate analysis. This section covers common cleaning tasks such as handling missing values, duplicates, renaming, type conversion, and applying functions._

---

In [11]:
df.isna().sum()

id                    0
age                   0
salary                0
department            0
join_date             0
performance_score    53
dtype: int64

In [12]:
# Fill missing `performance_score` values with the median:

df_filled = df.fillna({'performance_score': df['performance_score'].median()})

In [13]:
df.dropna()

     id  age    salary department  join_date  performance_score
0     1   56  81832.34         HR 2022-08-31                3.0
1     2   69  65486.98      Sales 2022-11-11                1.0
2     3   46  27209.45      Sales 2022-04-28                3.0
3     4   32  42736.49  Marketing 2022-01-17                3.0
4     5   60  69003.67      Sales 2022-09-15                1.0
..   ..  ...       ...        ...        ...                ...
500   1   56  81832.34         HR 2022-08-31                3.0
501   2   69  65486.98      Sales 2022-11-11                1.0
502   3   46  27209.45      Sales 2022-04-28                3.0
503   4   32  42736.49  Marketing 2022-01-17                3.0
504   5   60  69003.67      Sales 2022-09-15                1.0

[452 rows x 6 columns]

In [14]:
df_dropped = df.dropna()

In [15]:
df_dropped.shape

(452, 6)

In [16]:
df.duplicated().sum()

5

In [17]:
df_no_dupes = df.drop_duplicates()

In [18]:
df_replaced = df.replace({'department': {'HR': 'Human Resources'}})

In [19]:
df['salary'] = df['salary'].astype(int)

In [20]:
df_renamed = df.rename(columns={'salary': 'annual_salary'})

In [21]:
# apply example - add 10 to age
df['age_plus_10'] = df['age'].apply(lambda x: x + 10)

In [22]:
# applymap example (only on numeric columns)
df_numeric = df.select_dtypes(include=np.number)
df_numeric_plus_one = df_numeric.applymap(lambda x: x + 1)

C:\Users\arunk\AppData\Local\Temp\ipykernel_9392\4254895091.py:3: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df_numeric_plus_one = df_numeric.applymap(lambda x: x + 1)

In [23]:
# map example on department column to get code
dept_map = {'HR': 1, 'Engineering': 2, 'Sales': 3, 'Marketing': 4}
df['dept_code'] = df['department'].map(dept_map)

# 🎯 4. Selecting & Filtering Data

This section demonstrates how to select and filter data in a DataFrame using various methods.

---

In [24]:
df.loc[0:5, ['id', 'age', 'department']]      # label based indexing

   id  age   department
0   1   56           HR
1   2   69        Sales
2   3   46        Sales
3   4   32    Marketing
4   5   60        Sales
5   6   25  Engineering

In [25]:
df.iloc[0:5, 0:3]                             # position based indexing

   id  age  salary
0   1   56   81832
1   2   69   65486
2   3   46   27209
3   4   32   42736
4   5   60   69003

In [26]:
df.query('age > 30 and department == "Sales"')  # query rows

,id,age,salary,department,join_date,performance_score,age_plus_10,dept_code
1,2,69,65486,Sales,2022-11-11,1.0,79,3
2,3,46,27209,Sales,2022-04-28,3.0,56,3
4,5,60,69003,Sales,2022-09-15,1.0,70,3
7,8,56,61619,Sales,2022-05-18,1.0,66,3
8,9,36,36096,Sales,2020-03-24,3.0,46,3
...,...,...,...,...,...,...,...,...
494,495,49,52801,Sales,2020-08-25,4.0,59,3
497,498,57,28900,Sales,2021-04-27,3.0,67,3
501,2,69,65486,Sales,2022-11-11,1.0,79,3
502,3,46,27209,Sales,2022-04-28,3.0,56,3
504,5,60,69003,Sales,2022-09-15,1.0,70,3

In [27]:
df.filter(items=['id', 'salary'])             # filter columns by name

     id  salary
0     1   81832
1     2   65486
2     3   27209
3     4   42736
4     5   69003
..   ..     ...
500   1   81832
501   2   65486
502   3   27209
503   4   42736
504   5   69003

[505 rows x 2 columns]

In [28]:
df.where(df['age'] > 50).head()               # keep values where condition True else NaN

,id,age,salary,department,join_date,performance_score,age_plus_10,dept_code
0,1.0,56.0,81832.0,HR,2022-08-31,3.0,66.0,1.0
1,2.0,69.0,65486.0,Sales,2022-11-11,1.0,79.0,3.0
2,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
4,5.0,60.0,69003.0,Sales,2022-09-15,1.0,70.0,3.0

In [29]:
df.mask(df['age'] <= 50).head()               # keep values where condition False else NaN

,id,age,salary,department,join_date,performance_score,age_plus_10,dept_code
0,1.0,56.0,81832.0,HR,2022-08-31,3.0,66.0,1.0
1,2.0,69.0,65486.0,Sales,2022-11-11,1.0,79.0,3.0
2,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
4,5.0,60.0,69003.0,Sales,2022-09-15,1.0,70.0,3.0

In [30]:
df.sample(5)                                  # random sample of rows

,id,age,salary,department,join_date,performance_score,age_plus_10,dept_code
299,300,54,47664,HR,2020-12-08,1.0,64,1
197,198,58,34111,Marketing,2020-10-31,1.0,68,4
472,473,52,52562,Sales,2020-02-11,2.0,62,3
485,486,54,64740,Engineering,2020-09-22,4.0,64,2
243,244,21,58083,Sales,2022-01-13,NaN,31,3

In [31]:
df.nlargest(3, 'salary')                       # top 3 highest salaries

,id,age,salary,department,join_date,performance_score,age_plus_10,dept_code
226,227,34,96183,Engineering,2022-07-07,NaN,44,2
402,403,63,88600,HR,2021-07-14,4.0,73,1
362,363,47,86686,Marketing,2020-05-25,NaN,57,4

In [32]:
df.nsmallest(3, 'age')                         # 3 youngest employees

,id,age,salary,department,join_date,performance_score,age_plus_10,dept_code
101,102,18,47600,Engineering,2022-05-23,NaN,28,2
106,107,18,54840,Engineering,2022-11-01,NaN,28,2
138,139,18,36523,HR,2022-08-13,3.0,28,1

# 📊 5. Aggregation & Statistics

Aggregation and statistical functions help summarize and understand data distributions and relationships.

---

In [33]:
df.count()       # count non-nulls per column

id                   505
age                  505
salary               505
department           505
join_date            505
performance_score    452
age_plus_10          505
dept_code            505
dtype: int64

In [34]:
df['salary'].sum()

25064899

In [35]:
df['age'].mean()

44.3029702970297

In [36]:
df['age'].median()

45.0

In [37]:
df['salary'].std()

14979.868919068844

In [38]:
df['salary'].var()

224396472.83248475

In [39]:
df['age'].min()

18

In [40]:
df['salary'].max()

96183

In [41]:
df.corr()

ValueError: could not convert string to float: 'HR'

In [42]:
df.cov()

ValueError: could not convert string to float: 'HR'

In [43]:
# Group by department
df.groupby('department')['salary'].mean()

department
Engineering    51188.603306
HR             50228.211679
Marketing      49222.079646
Sales          47968.044776
Name: salary, dtype: float64

In [44]:
# Pivot table example (mean salary per department per performance score)
pd.pivot_table(df, values='salary', index='department', columns='performance_score', aggfunc='mean')

performance_score,1.0,2.0,3.0,4.0,5.0
department,,,,,
Engineering,56441.450000,49032.148148,51191.424242,49191.944444,44663.000000
HR,45943.047619,47108.923077,52643.695652,55766.650000,47925.900000
Marketing,50614.681818,49748.047619,45061.964286,56148.150000,50232.125000
Sales,48792.923077,47152.000000,47481.974359,46283.045455,50121.066667

In [45]:
# Aggregation with agg()
df.agg({'age': ['min', 'max', 'mean'], 'salary': ['sum', 'mean']})

           age        salary
min   18.00000           NaN
max   69.00000           NaN
mean  44.30297  4.963346e+04
sum        NaN  2.506490e+07

In [46]:
# Cumulative sum and product of salary
df['cumsum_salary'] = df['salary'].cumsum()
df['cumprod_age'] = df['age'].cumprod()

# 🛠️ 6. Modifying Data

In [47]:
# Insert a new column
df.insert(1, 'new_col', 'test')

In [48]:
# Concatenate DataFrames
df2 = df.head(10).copy()
df_concat = pd.concat([df, df2], ignore_index=True)

In [49]:
# Assign to add a calculated column
df = df.assign(salary_k = df['salary'] / 1000)

In [50]:
# Melt - long format
df_melt = pd.melt(df, id_vars=['id'], value_vars=['age', 'salary_k'])

In [51]:
# Pivot - wide format
df_pivot = df_melt.pivot(index='id', columns='variable', values='value')

ValueError: Index contains duplicate entries, cannot reshape

In [52]:
# Explode - create one row per list element
df_explode = pd.DataFrame({'id': [1, 2], 'colors': [['red', 'blue'], ['green']]})
df_exploded = df_explode.explode('colors')

# 🔗 7. Merging & Joining

In [53]:
df_left = df.head(10)
df_right = df[['id', 'department']].tail(10)

In [54]:
# Merge on 'id'
df_merged = df_left.merge(df_right, on='id', how='inner')

In [55]:
# Join (set index first)
df_left = df_left.set_index('id')
df_right = df_right.set_index('id')
df_joined = df_left.join(df_right, lsuffix='_left', rsuffix='_right')

In [56]:
# Concatenate (again)
df_concat = pd.concat([df_left, df_right], axis=0)

## 📑 8. Sorting Data

In [57]:
df.sort_values(by='salary', ascending=False).head()  # sort descending by salary

,id,new_col,age,salary,department,join_date,performance_score,age_plus_10,dept_code,cumsum_salary,cumprod_age,salary_k
226,227,test,34,96183,Engineering,2022-07-07,NaN,44,2,11467018,0,96.183
402,403,test,63,88600,HR,2021-07-14,4.0,73,1,20129037,0,88.600
362,363,test,47,86686,Marketing,2020-05-25,NaN,57,4,18106100,0,86.686
331,332,test,33,84060,Engineering,2020-12-15,4.0,43,2,16511689,0,84.060
126,127,test,51,82847,Engineering,2020-04-02,3.0,61,2,6519492,0,82.847

In [58]:
df.sort_index().head()  # sort by index

,id,new_col,age,salary,department,join_date,performance_score,age_plus_10,dept_code,cumsum_salary,cumprod_age,salary_k
0,1,test,56,81832,HR,2022-08-31,3.0,66,1,81832,56,81.832
1,2,test,69,65486,Sales,2022-11-11,1.0,79,3,147318,3864,65.486
2,3,test,46,27209,Sales,2022-04-28,3.0,56,3,174527,177744,27.209
3,4,test,32,42736,Marketing,2022-01-17,3.0,42,4,217263,5687808,42.736
4,5,test,60,69003,Sales,2022-09-15,1.0,70,3,286266,341268480,69.003

### 🔤 9. String Operations

In [59]:
df['department'].str.lower()

0             hr
1          sales
2          sales
3      marketing
4          sales
         ...
500           hr
501        sales
502        sales
503    marketing
504        sales
Name: department, Length: 505, dtype: object

In [60]:
df['department'].str.upper()

0             HR
1          SALES
2          SALES
3      MARKETING
4          SALES
         ...
500           HR
501        SALES
502        SALES
503    MARKETING
504        SALES
Name: department, Length: 505, dtype: object

In [61]:
df['department'].str.strip()

0             HR
1          Sales
2          Sales
3      Marketing
4          Sales
         ...
500           HR
501        Sales
502        Sales
503    Marketing
504        Sales
Name: department, Length: 505, dtype: object

In [62]:
df['department'].str.replace('Sales', 'Sales Dept')

0              HR
1      Sales Dept
2      Sales Dept
3       Marketing
4      Sales Dept
          ...
500            HR
501    Sales Dept
502    Sales Dept
503     Marketing
504    Sales Dept
Name: department, Length: 505, dtype: object

In [63]:
df['department'].str.contains('Eng').head()

0    False
1    False
2    False
3    False
4    False
Name: department, dtype: bool

In [64]:
df['department'].str.extract('(Eng.*)')

       0
0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
..   ...
500  NaN
501  NaN
502  NaN
503  NaN
504  NaN

[505 rows x 1 columns]

In [65]:
df['department'].str.findall('[aeiou]')

0             []
1         [a, e]
2         [a, e]
3      [a, e, i]
4         [a, e]
         ...
500           []
501       [a, e]
502       [a, e]
503    [a, e, i]
504       [a, e]
Name: department, Length: 505, dtype: object

In [66]:
df['department'].str.split('a')

0              [HR]
1          [S, les]
2          [S, les]
3      [M, rketing]
4          [S, les]
           ...
500            [HR]
501        [S, les]
502        [S, les]
503    [M, rketing]
504        [S, les]
Name: department, Length: 505, dtype: object

### 🕒 10. Date & Time Handling

In [67]:
pd.to_datetime(df['join_date'])

0     2022-08-31
1     2022-11-11
2     2022-04-28
3     2022-01-17
4     2022-09-15
         ...
500   2022-08-31
501   2022-11-11
502   2022-04-28
503   2022-01-17
504   2022-09-15
Name: join_date, Length: 505, dtype: datetime64[ns]

In [68]:
df['join_date'].dt.year.head()

0    2022
1    2022
2    2022
3    2022
4    2022
Name: join_date, dtype: int32

In [69]:
df['join_date'].dt.month.head()

0     8
1    11
2     4
3     1
4     9
Name: join_date, dtype: int32

In [70]:
df['join_date'].dt.day.head()

0    31
1    11
2    28
3    17
4    15
Name: join_date, dtype: int32

In [71]:
df['join_date'].dt.hour.head()

0    0
1    0
2    0
3    0
4    0
Name: join_date, dtype: int32

In [72]:
df['join_date'].dt.minute.head()

0    0
1    0
2    0
3    0
4    0
Name: join_date, dtype: int32

In [73]:
df['join_date'].dt.second.head()

0    0
1    0
2    0
3    0
4    0
Name: join_date, dtype: int32

In [74]:
df['join_date'].dt.dayofweek.head()

0    2
1    4
2    3
3    0
4    3
Name: join_date, dtype: int32